%measure particle velocity using calibrated pv mic for a sine sound
%generated by some outside source
%need to know the frequency of the sound beforehand
function [test_freq,pv]=measure_pv_arbitrary(pv_calib_filename,test_freq)

if(~isempty(pv_calib_filename))
    if ~exist(strcat(pv_calib_filename,'.mat'),"file")
        error(strcat(pv_calib_filename,' does not exist'));
    else
        load(pv_calib_filename, '-mat', 'So2','freqs');
    end
else
    error('need to specify mat file for pv mic calibration data');
end

pv_usb_samp_rate = 8000; %Hz, need to be 1000-8000 Hz & multiple of 1000
pv_usb_port = "COM5"; %check with serialportlist()
measure_duration = 1; %s

if max(test_freq)> pv_usb_samp_rate/2
    disp('ERROR: freq is greater than the Nyquist frequency');
    return;
end

%create PV USB mic instance
pv_usb_bit_to_voltage = 2.5/2^16; %conversion factor in bits per voltage (can be optional)
pv_usb_samp_rate = round(pv_usb_samp_rate, -3);
pv_usb_mic = PvMicUSB(pv_usb_port,pv_usb_samp_rate);
pv_usb_mic.On();

disp('starting '+measure_duration+' s sound acquisition')
in = pv_usb_mic.Record(ceil(measure_duration*pv_usb_samp_rate));
pv_usb_mic.delete();
disp('Done!')

highpass=20;
lowpass=1500;

%filter unwanted frequencies, then fit sine
[b,a]=butter(4,[highpass lowpass]./(pv_usb_samp_rate/2));
in=filtfilt(b,a,in);
[amp, ~]=fit_sin(in,freq,pv_usb_samp_rate);

figure(1);
plot(in);
axis tight;

%calculate pv from mic reading
pv=amp*interp1(freqs, So2(:,1), test_freq, 'makima', 'extrap'); %divide amplitude by mic sensitivity to get pv in m/s


end